//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resourses.BLL.App.DTO.Ranks {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Ranks {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ranks() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resourses.BLL.App.DTO.Ranks.Ranks", typeof(Ranks).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxExperience.
        /// </summary>
        public static string MaxExperience {
            get {
                return ResourceManager.GetString("MaxExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinExperience.
        /// </summary>
        public static string MinExperience {
            get {
                return ResourceManager.GetString("MinExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NextRank.
        /// </summary>
        public static string NextRank {
            get {
                return ResourceManager.GetString("NextRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NextRankId.
        /// </summary>
        public static string NextRankId {
            get {
                return ResourceManager.GetString("NextRankId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreviousRank.
        /// </summary>
        public static string PreviousRank {
            get {
                return ResourceManager.GetString("PreviousRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreviousRankId.
        /// </summary>
        public static string PreviousRankId {
            get {
                return ResourceManager.GetString("PreviousRankId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProfileRanks.
        /// </summary>
        public static string ProfileRanks {
            get {
                return ResourceManager.GetString("ProfileRanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RankCode.
        /// </summary>
        public static string RankCode {
            get {
                return ResourceManager.GetString("RankCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RankColor.
        /// </summary>
        public static string RankColor {
            get {
                return ResourceManager.GetString("RankColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RankDescription.
        /// </summary>
        public static string RankDescription {
            get {
                return ResourceManager.GetString("RankDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RankIcon.
        /// </summary>
        public static string RankIcon {
            get {
                return ResourceManager.GetString("RankIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RankTextColor.
        /// </summary>
        public static string RankTextColor {
            get {
                return ResourceManager.GetString("RankTextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RankTitle.
        /// </summary>
        public static string RankTitle {
            get {
                return ResourceManager.GetString("RankTitle", resourceCulture);
            }
        }
    }
}
