//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resourses.BLL.App.DTO.ChatRoles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ChatRoles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChatRoles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resourses.BLL.App.DTO.ChatRoles.ChatRoles", typeof(ChatRoles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can edit all messages?.
        /// </summary>
        public static string CanEditAllMessages {
            get {
                return ResourceManager.GetString("CanEditAllMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can edit members roles?.
        /// </summary>
        public static string CanEditMembers {
            get {
                return ResourceManager.GetString("CanEditMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can edit own messages?.
        /// </summary>
        public static string CanEditMessages {
            get {
                return ResourceManager.GetString("CanEditMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can rename room?.
        /// </summary>
        public static string CanRenameRoom {
            get {
                return ResourceManager.GetString("CanRenameRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can write messages?.
        /// </summary>
        public static string CanWriteMessages {
            get {
                return ResourceManager.GetString("CanWriteMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string ChatMembers {
            get {
                return ResourceManager.GetString("ChatMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role title.
        /// </summary>
        public static string RoleTitle {
            get {
                return ResourceManager.GetString("RoleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role title translated.
        /// </summary>
        public static string RoleTitleValue {
            get {
                return ResourceManager.GetString("RoleTitleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role title translated (ID).
        /// </summary>
        public static string RoleTitleValueId {
            get {
                return ResourceManager.GetString("RoleTitleValueId", resourceCulture);
            }
        }
    }
}
