//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resourses.Views.Identity {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Identity {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Identity() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resourses.Views.Identity.Identity", typeof(Identity).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Already have an account? Login.
        /// </summary>
        public static string AlreadyHave {
            get {
                return ResourceManager.GetString("AlreadyHave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change avatar.
        /// </summary>
        public static string AvatarEditNav {
            get {
                return ResourceManager.GetString("AvatarEditNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Avatar.
        /// </summary>
        public static string AvatarHeader {
            get {
                return ResourceManager.GetString("AvatarHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Avatar was updated successfully..
        /// </summary>
        public static string AvatarUpdateStatusSuccess {
            get {
                return ResourceManager.GetString("AvatarUpdateStatusSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Blacklist.
        /// </summary>
        public static string BlackListNav {
            get {
                return ResourceManager.GetString("BlackListNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current email.
        /// </summary>
        public static string CurrentEmail {
            get {
                return ResourceManager.GetString("CurrentEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change email.
        /// </summary>
        public static string EmailEditNav {
            get {
                return ResourceManager.GetString("EmailEditNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change email.
        /// </summary>
        public static string EmailHeader {
            get {
                return ResourceManager.GetString("EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirmation link to change email sent. Please check your email..
        /// </summary>
        public static string EmailUpdateStatusConfirmationSend {
            get {
                return ResourceManager.GetString("EmailUpdateStatusConfirmationSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email was updated successfully..
        /// </summary>
        public static string EmailUpdateStatusSuccess {
            get {
                return ResourceManager.GetString("EmailUpdateStatusSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your email is unchanged..
        /// </summary>
        public static string EmailUpdateStatusUnchanged {
            get {
                return ResourceManager.GetString("EmailUpdateStatusUnchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Forgot your password?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The {0} field is not a valid e-mail address..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The {0} field is not a valid phone number..
        /// </summary>
        public static string InvalidPhone {
            get {
                return ResourceManager.GetString("InvalidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid login attempt..
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log in.
        /// </summary>
        public static string LoginHeader {
            get {
                return ResourceManager.GetString("LoginHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New email.
        /// </summary>
        public static string NewEmail {
            get {
                return ResourceManager.GetString("NewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New password confirmation.
        /// </summary>
        public static string NewPasswordConfirm {
            get {
                return ResourceManager.GetString("NewPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your password has been changed..
        /// </summary>
        public static string PasswordDataUpdateStatusSuccess {
            get {
                return ResourceManager.GetString("PasswordDataUpdateStatusSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change password.
        /// </summary>
        public static string PasswordEditNav {
            get {
                return ResourceManager.GetString("PasswordEditNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change password.
        /// </summary>
        public static string PasswordHeader {
            get {
                return ResourceManager.GetString("PasswordHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The password and confirmation password do not match..
        /// </summary>
        public static string PasswordMatchError {
            get {
                return ResourceManager.GetString("PasswordMatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Personal Data.
        /// </summary>
        public static string PersonalDataHeader {
            get {
                return ResourceManager.GetString("PersonalDataHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your account contains personal data that you have given us..
        /// </summary>
        public static string PersonalDataWarning1 {
            get {
                return ResourceManager.GetString("PersonalDataWarning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This page allows you to download or delete that data..
        /// </summary>
        public static string PersonalDataWarning2 {
            get {
                return ResourceManager.GetString("PersonalDataWarning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Deleting this data will permanently remove your account, and this cannot be recovered..
        /// </summary>
        public static string PersonalDataWarning3 {
            get {
                return ResourceManager.GetString("PersonalDataWarning3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Privacy and Security.
        /// </summary>
        public static string PrivacyHeader {
            get {
                return ResourceManager.GetString("PrivacyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Privacy and security.
        /// </summary>
        public static string PrivacyNav {
            get {
                return ResourceManager.GetString("PrivacyNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your profile has been updated..
        /// </summary>
        public static string ProfileDataUpdateStatusSuccess {
            get {
                return ResourceManager.GetString("ProfileDataUpdateStatusSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error. That username is already taken!.
        /// </summary>
        public static string ProfileDataUpdateStatusUsernameExists {
            get {
                return ResourceManager.GetString("ProfileDataUpdateStatusUsernameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit profile.
        /// </summary>
        public static string ProfileEditNav {
            get {
                return ResourceManager.GetString("ProfileEditNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile.
        /// </summary>
        public static string ProfileHeader {
            get {
                return ResourceManager.GetString("ProfileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create a new account.
        /// </summary>
        public static string RegisterHeader {
            get {
                return ResourceManager.GetString("RegisterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Register as a new user.
        /// </summary>
        public static string RegisterNew {
            get {
                return ResourceManager.GetString("RegisterNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remember me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
    }
}
